---
version: '3'
tasks:
  install:
    desc: 🧱 Install React dependencies
    cmds:
      - npm install
  lint:
    desc: 🧹 Lint React code
    cmds:
      - npm run lint:fix
  lint-check:
    desc: 🧹 Lint React code
    cmds:
      - npm run lint
  test:
    desc: 🧪 Test React code
    cmds:
      - npm run test:coverage
  build:
    desc: 🏗️ Build React code
    cmds:
      - npm run build
  dev:
    desc: 🚀 Start React development server
    cmds:
      - npm run dev