---
name: af-component-react Framework
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test-framework:
    name: "Test Framework"
    runs-on: "ubuntu-latest"
    container:
      image: ghcr.io/astral-sh/uv:python3.11-bookworm
    steps:
      - name: Checkout
        uses: "actions/checkout@v5"
      - name: Install Node.js
        run: |
          apt-get update && apt-get install -y nodejs npm --no-install-recommends
      - name: Render template
        uses: datarobot-oss/copier-template-validator@main
        with:
          working-directory: .
          rendered-dir: ./rendered
      - name: Install dependencies
        shell: sh
        working-directory: ./rendered/frontend_web
        run: |
          npm install --include=optional
      - name: Run linter
        shell: sh
        working-directory: ./rendered/frontend_web
        run: |
          npm run lint
      - name: Run tests
        shell: sh
        working-directory: ./rendered/frontend_web
        run: |
          npm run test
